### PR TITLE
UART USB port info

### PR DESCRIPTION
**Pull request by lboue**
UART USB port info

### CODE REVIEW

**Comment by lboue** [comment]
@luar123
Is is OK for you?

**Comment by luar123** [comment]
Is there a benefit of using two cables? I am always connecting only the uart port for flashing+monitoring. The usb port should be able to do the same + JTAG debugging.

**Comment by lboue** [comment]
With the C6 board, I didn't have the logs visible on the "USB" port.

[ESP32 Dev Boards with two USB ports](https://www.espboards.dev/blog/why-esp32-dev-boards-2-usb-c/)

> Having two USB ports on an ESP32 development board provides more flexibility in terms of connectivity options. For example, you can use one port for programming and debugging while using the other port for other purposes such as power supply, data transfer, or serial communication.

**Comment by luar123** [comment]
Yes sure, you can use both. If you want to get log out at the USB port you would need to change the logger in the .yaml file.

**Pull request merged**
